language: rust
rust:
  stable
cache: cargo
before_script:
  if [[ $(cargo install --list | grep wasm-pack | wc -c) -eq 0 ]]; then cargo install wasm-pack; fi
script:
  wasm-pack build --target web
before_deploy:
  xz -zec pkg/symatem_bg.wasm > symatem.wasm.xz
deploy:
  edge: true
  provider: releases
  token: $GITHUB_TOKEN
  file: symatem.wasm.xz
  on:
    tags: true
